### ISSUE TITLE
Mocking final methods should fail early and with a descriptive error.

### ISSUE THREAD

**Issue by olibye** [jmock-developers/jmock-library#81]
I've been informed of this second hand, it seems to be true. I'll try and come up with a test.

**Comment by npryce** [comment]
It's a limitation we found difficult to address because we didn't do bytecode rewriting. The difficulty is that jmock would have to override final methods in order to detect when they are called during an expectation -- but cannot because they are final.

Our opinion at the time was that it was only a problem in the "legacy" package, which provided support for getting legacy code under test. In that situation, nothing's perfect! If you're working on your own legacy code, it's safe to remove final modifiers or introduce interfaces. If mocking third party code, it could be worth introducing an interface between your code and the third party code.

**Comment by olibye** [comment]
Yep, good point. They can use an interface, and it's our final method, so we've got options.
